package envfile

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

const header = "# Generated by vaultpull — do not edit manually\n"

// Write writes secrets to the given file path in KEY=VALUE format.
// Existing file is overwritten. Keys are sorted for determinism.
func Write(path string, secrets map[string]string) error {
	keys := make([]string, 0, len(secrets))
	for k := range secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString(header)
	for _, k := range keys {
		v := secrets[k]
		if needsQuoting(v) {
			v = fmt.Sprintf(`"%s"`, strings.ReplaceAll(v, `"`, `\"`))
		}
		fmt.Fprintf(&sb, "%s=%s\n", k, v)
	}

	return os.WriteFile(path, []byte(sb.String()), 0600)
}

// needsQuoting returns true if the value contains spaces or special chars.
func needsQuoting(v string) bool {
	return strings.ContainsAny(v, " \t\n#$'`")
}
